### ISSUE TITLE
how to install using composer?

### ISSUE THREAD

**Issue by DiegoWtf** [yugene/Gearman-Monitor#10]
i add "yugene/gearman-monitor"      : "*" in my compose.json
and i see
Problem 1
    - The requested package yugene/gearman-monitor could not be found in any version, there may be a typo in the package name.

**Comment by yugene** [comment]
Gearman-monitor is not available through Packagist, so you have to add the link to the repo. See the following: http://stackoverflow.com/questions/12954051/use-php-composer-to-clone-git-repo
